# Generated by Django 5.2.3 on 2025-08-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesheet',
            unique_together={('subject', 'date', 'schedule')},
        ),
    ]
