# Generated by Django 5.2.3 on 2025-08-31 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesheet',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sheets', to='exams.subject'),
        ),
        migrations.AlterField(
            model_name='exambooking',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='exams.subject'),
        ),
    ]
