# Generated by Django 5.2.3 on 2025-10-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_customuser_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('r_date', models.DateField()),
                ('out_of_marks', models.IntegerField(default=0)),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=100)),
                ('faculty_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin_results',
            },
        ),
    ]
