# Generated by Django 5.2.5 on 2025-11-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_adminresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminresult',
            name='out_of_marks',
            field=models.CharField(default=0),
        ),
    ]
