# Generated by Django 5.2.5 on 2025-11-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_timeschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSchedule',
        ),
    ]
