# Generated by Django 5.2.5 on 2025-11-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_timeschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatingarrangement',
            name='room',
        ),
        migrations.AlterUniqueTogether(
            name='seatingarrangement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='seatingarrangement',
            name='student',
        ),
        migrations.RemoveField(
            model_name='seatingarrangement',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='subject',
        ),
        migrations.DeleteModel(
            name='ExamRoom',
        ),
        migrations.DeleteModel(
            name='SeatingArrangement',
        ),
        migrations.DeleteModel(
            name='TimeSchedule',
        ),
    ]
