# Generated by Django 5.2.5 on 2025-11-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_examschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomassignment',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.examduration'),
        ),
    ]
